{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "fd63d8b7",
   "metadata": {},
   "outputs": [],
   "source": [
    "#This is creating the basis itself; it only depends on the interval that you want the grid\n",
    "struct Rational <: Basis\n",
    "    GD::GridInterval\n",
    "end\n",
    "\n",
    "#This defines the \"domain\" that the basis itself is defined on\n",
    "cfd(sp::Rational) = ℤ #QUESTION: what does cfd stand for? \n",
    "\n",
    "#This defines the dimension of the basis\n",
    "function dim(sp::Rational)\n",
    "    Inf\n",
    "end\n",
    "\n",
    "function testconv(f::BasisExpansion{T}) where T <: Rational\n",
    "    nm = N₋(length(f.c))\n",
    "    testconv(f.c[1:nm] |> reverse) && testconv(f.c[nm+1:end])\n",
    "end\n",
    "\n",
    "#Chops off coefficients less than 1e-15 and expands in Rational basis with those coeffs\n",
    "function chop(f::BasisExpansion{T}) where T <: Rational\n",
    "    nm = N₋(length(f.c)) #Int(floor(N/2))\n",
    "    vm = chop(copy(f.c[1:nm]) |> reverse) |> reverse; #negative coeffs (chopping terms smaller than 1e-15)\n",
    "    vp = chop(copy(f.c[nm+1:end])); #positive coeffs (chopping terms smaller than 1e-15)\n",
    "    k = max(length(vm),length(vp)) #take max of length of vm or vp\n",
    "    vm = pad(vm |> reverse,k) |> reverse #pad beginning with zeros to be equal to max length\n",
    "    vp = pad(vp,k) #pad end with zeros to be equal to max length\n",
    "    BasisExpansion(f.basis,vcat(vm,vp)) #expand in Rational basis using truncated coeffs with 1e-15 cutoff\n",
    "end\n",
    "\n",
    "#stealing code from Tom's 586 FFT tutorial\n",
    "mfftshift = x -> circshift(fftshift(x), isodd(length(x)) ? 1 : 0)\n",
    "mfft = x -> fftshift(fft(fftshift(x),1)) # fft(x,1) is used so that\n",
    "# when we operate on matrices below, the behavior is as desired.\n",
    "mifft = x -> mfftshift(ifft(mfftshift(x),1))\n",
    "mgrid = (n,L) -> -L .+ 2*L*(0:n-1)/n\n",
    "shift_mgrid = (n,L) -> (((-L .+ 2*L*(0:n-1)/n)./(2*L)).+(1/2)).*(2*π)\n",
    "Pgrid = n -> 2*(0:n-1)/n .- 1\n",
    "\n",
    "N₋ = N -> convert(Int64,floor(N/2))\n",
    "N₊ = N -> convert(Int64,floor((N-1)/2))\n",
    "\n",
    "function mdft(v)\n",
    "    if iseven(length(v))\n",
    "        return mfft(v)/length(v)\n",
    "    else # all this work for odd...\n",
    "        m = length(v)\n",
    "        mm = m ÷ 2\n",
    "        σ = 1im*pi/m\n",
    "        rot = exp(mm*σ)\n",
    "        σ = exp(σ)\n",
    "        w = mfft(v)\n",
    "        @inbounds for i = 1:m\n",
    "            w[i] *= rot\n",
    "            rot /= σ\n",
    "        end\n",
    "        return w/m\n",
    "    end\n",
    "end\n",
    "\n",
    "function midft(v)\n",
    "    if iseven(length(v))\n",
    "        return mifft(v*length(v))\n",
    "    else\n",
    "        w = copy(v)\n",
    "        m = length(v)\n",
    "        mm = m ÷ 2\n",
    "        σ = 1im*pi/m\n",
    "        rot = exp(mm*σ)\n",
    "        σ = exp(σ)\n",
    "        @inbounds for i = 1:m\n",
    "            w[i] /= rot\n",
    "            rot /= σ\n",
    "        end\n",
    "        return mifft(w*m)\n",
    "    end\n",
    "end\n",
    "\n",
    "function (P::BasisExpansion{Rational})(k::Number) # Horner's method\n",
    "    x = P.basis.GD.D.imap(k) #!!!!!!!!!!need to check/input this to be #x = ((k-1im)/(k+1im));\n",
    "    m = length(P.c)\n",
    "    mm = convert(Int64,floor( m/2 )) #basically N₋(N);\n",
    "    y = x^(-mm); \n",
    "    sum = P.c[1]*y\n",
    "    for i = 2:length(P.c) # probably should do Horner from the zero mode outwards\n",
    "        y  =  y.*x\n",
    "        sum += P.c[i]*y\n",
    "    end\n",
    "    return sum\n",
    "end"
   ]
  }
 ],
 "metadata": {
  "@webio": {
   "lastCommId": null,
   "lastKernelId": null
  },
  "kernelspec": {
   "display_name": "Julia 1.8.5",
   "language": "julia",
   "name": "julia-1.8"
  },
  "language_info": {
   "file_extension": ".jl",
   "mimetype": "application/julia",
   "name": "julia",
   "version": "1.8.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
